services:
  db:
    image: mysql:8.0
    container_name: muscle_db
    command: mysqld --innodb_use_native_aio=0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: muscle_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    env_file:
      - ./backend.env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  mysql_data:
